sudo: required
language: java
services:
  - docker
before_script:
  - unset _JAVA_OPTIONS # Prevents issues such as formatting the test outputs
  - sudo mount --make-rshared /
  - wget -nv https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz
  - tar -xvf openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz
  - cd openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit
  - export PATH=`pwd`:$PATH
  - cd ..
  - mv scripts/daemon.json /etc/docker/
  - oc cluster up
  - chmod +x scripts/travisTest.sh
  - cd finish/
script: ../scripts/travisTest.sh
branches:
  only: 
  - master
  - qa
<<<<<<< HEAD
  - mai/travis-test-upgrade
=======
  - dev
>>>>>>> 2a447c45195eb107d1347a556082e4b8cc3bdd2f
